### ISSUE TITLE
feat: To-do API 문서 생성

### ISSUE THREAD

**Issue by jmkim0** [jmkim0/todo-app#3]
**Is your feature request related to a problem? Please describe.**
To-do API 정의 필요

**Describe the solution you'd like**
- [ ] To-do mock controller 구현
- [ ] To-do mock controller test slice 구현
- [ ] API 문서 생성

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
